### ISSUE TITLE
Normal Distribution

### ISSUE THREAD

**Issue by FlippieCoetser** [Hurna/Hurna-Core#1]
I tried using your calculator to plot the normal distribution based on the equation from wiki: https://en.wikipedia.org/wiki/Normal_distribution. but I was to able to make it work. Is this use case supported?

**Comment by michael-jeulinl** [comment]
The use case is supported and you have built-in function to make this quickly :
The commande to use is "**Normal(mean, standard deviation, variable)**"

The image below illustrate this use case.
![Normal_Distribution](https://user-images.githubusercontent.com/1020428/55241533-92be3d80-523b-11e9-858f-c666d186a3fe.png)

I hope it helped.
Regards.

**Comment by FlippieCoetser** [comment]
@michael-jeulinl Thanks for pointing me the right direction! great platform!

**Comment by michael-jeulinl** [comment]
Thank you !

**Comment by FlippieCoetser** [comment]
@michael-jeulinl what am I missing here. 
This is probably a super stupid question,

When I click on the 'plus' sign and type Normal, I can see the expression, like below
![image](https://user-images.githubusercontent.com/3672126/55274875-c487e080-52dd-11e9-8f9b-a16047f0b309.png)

But how on earth do you add the three variables?

**Comment by michael-jeulinl** [comment]
You just have to replace each parameter < XXX > by what you want (numerical value or variable).
If those parameter are variable, it may better to declare them before (e.g. m = 0.5 on the first add, s = 0.1 on the second line and then just copy past this text for the third line) : 
f(x) = Normal(m,s,x, false)

**Comment by michael-jeulinl** [comment]
You may also resize the input panel to have better view for handling your inputs :
![screen_resize_input](https://user-images.githubusercontent.com/1020428/55275107-7d9bea00-52e1-11e9-9fe2-ea905e275369.png)

**Comment by FlippieCoetser** [comment]
It's working! Super! Is it also possible to do surface plots (x, y, z axis)?

**Comment by michael-jeulinl** [comment]
Use the Integral function as in :
https://demo.hurna.io/#path=equation_solver/graphical --> Last model (Integral)
